#=== CONFIGURACION DE MYSQL ===
spring.datasource.url=jdbc:mysql://localhost:3306/carepet?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Marzo_20
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#=== CONFIGURACION DE JPA/HIBERNATE ===
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


#=== CONFIGURACION DEL SERVIDOR ===
server.port=8080

#=== CONFIGURACION DE JWT ===
jwt.secret=mi-secret-key-super-segura-para-desarrollo-cambiar-en-produccion-minimo-256-bits-de-longitud
jwt.expiration=604800000